CREATE TABLE llm_trigger_runs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  assignment_id BIGINT NULL,
  template_version_id BIGINT NOT NULL,
  dataset_item_id BIGINT NULL,
  component_id VARCHAR(128) NOT NULL,
  provider_id BIGINT NOT NULL,
  model_name VARCHAR(128) NOT NULL,
  agent_run_id BIGINT NULL,
  status VARCHAR(30) NOT NULL,
  target_fields_json JSON NULL,
  input_snapshot_json JSON NULL,
  result_json JSON NULL,
  content_text LONGTEXT NULL,
  latency_ms BIGINT NULL,
  error_code VARCHAR(100) NULL,
  error_message VARCHAR(500) NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_llm_trigger_runs_task (task_id, created_at),
  KEY idx_llm_trigger_runs_assignment (assignment_id, created_at),
  KEY idx_llm_trigger_runs_agent_run (agent_run_id),
  CONSTRAINT fk_llm_trigger_runs_task FOREIGN KEY (task_id) REFERENCES tasks(id),
  CONSTRAINT fk_llm_trigger_runs_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id),
  CONSTRAINT fk_llm_trigger_runs_template_version FOREIGN KEY (template_version_id) REFERENCES template_versions(id),
  CONSTRAINT fk_llm_trigger_runs_item FOREIGN KEY (dataset_item_id) REFERENCES dataset_items(id),
  CONSTRAINT fk_llm_trigger_runs_provider FOREIGN KEY (provider_id) REFERENCES llm_providers(id),
  CONSTRAINT fk_llm_trigger_runs_agent_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id),
  CONSTRAINT fk_llm_trigger_runs_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT chk_llm_trigger_runs_status CHECK (status IN ('PENDING','RUNNING','SUCCESS','FAILED','RATE_LIMITED','MANUAL_REQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='Asynchronous LLM trigger execution records.';
