SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `agent_runs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `agent_type` varchar(32) NOT NULL,
  `submission_id` bigint DEFAULT NULL,
  `provider_id` bigint DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `prompt_version` varchar(64) DEFAULT NULL,
  `input_snapshot` json DEFAULT NULL COMMENT 'Prompt input snapshot for traceability; do not reconstruct it from mutable business tables.',
  `output_snapshot` json DEFAULT NULL COMMENT 'Raw or normalized model output for this concrete agent execution.',
  `status` varchar(24) NOT NULL DEFAULT 'PENDING',
  `error_message` text,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_agent_runs_submission` (`submission_id`,`created_at`),
  KEY `idx_agent_runs_status` (`status`,`created_at`),
  KEY `fk_agent_runs_provider` (`provider_id`),
  CONSTRAINT `fk_agent_runs_provider` FOREIGN KEY (`provider_id`) REFERENCES `llm_providers` (`id`),
  CONSTRAINT `fk_agent_runs_submission` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `chk_agent_runs_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'RUNNING',_utf8mb4'SUCCESS',_utf8mb4'FAILED',_utf8mb4'RATE_LIMITED',_utf8mb4'MANUAL_REQUIRED'))),
  CONSTRAINT `chk_agent_runs_type` CHECK ((`agent_type` in (_utf8mb4'AI_REVIEW',_utf8mb4'LLM_TRIGGER')))
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Concrete AI/LLM execution attempts, including retries and failures.';
CREATE TABLE `ai_review_configs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `provider_id` bigint DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `prompt_template` mediumtext,
  `output_schema_json` json DEFAULT NULL,
  `dimension_config_json` json DEFAULT NULL,
  `pass_threshold` decimal(5,2) DEFAULT NULL,
  `reject_threshold` decimal(5,2) DEFAULT NULL,
  `manual_threshold` decimal(5,2) DEFAULT NULL,
  `ai_reject_action` varchar(24) NOT NULL DEFAULT 'SUGGEST_ONLY' COMMENT 'Whether AI reject only suggests, returns to labeler, or requires manual review.',
  `max_retry` int NOT NULL DEFAULT '3',
  `agent_mode` varchar(24) NOT NULL DEFAULT 'DIRECT' COMMENT 'DIRECT | SUPERVISOR',
  `enabled_tools` json DEFAULT NULL COMMENT 'Enabled tool names list, null means all enabled',
  `max_iterations` int NOT NULL DEFAULT '10',
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_ai_review_configs_task` (`task_id`),
  KEY `fk_ai_review_configs_provider` (`provider_id`),
  KEY `fk_ai_review_configs_created_by` (`created_by`),
  CONSTRAINT `fk_ai_review_configs_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_ai_review_configs_provider` FOREIGN KEY (`provider_id`) REFERENCES `llm_providers` (`id`),
  CONSTRAINT `fk_ai_review_configs_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_agent_mode` CHECK ((`agent_mode` in (_utf8mb4'DIRECT',_utf8mb4'SUPERVISOR'))),
  CONSTRAINT `chk_ai_review_configs_reject_action` CHECK ((`ai_reject_action` in (_utf8mb4'SUGGEST_ONLY',_utf8mb4'RETURN_TO_LABELER',_utf8mb4'MANUAL_REVIEW')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Per-task AI review prompt, thresholds, provider, and reject routing policy.';
CREATE TABLE `ai_review_results` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `submission_id` bigint NOT NULL,
  `effective_run_id` bigint DEFAULT NULL COMMENT 'The agent run whose output is currently effective for this AI review result.',
  `provider_id` bigint DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'PENDING',
  `decision` varchar(24) DEFAULT NULL,
  `average_score` decimal(6,3) DEFAULT NULL,
  `dimension_scores` json DEFAULT NULL,
  `risk_flags` json DEFAULT NULL,
  `suggestion` text,
  `prompt_snapshot` mediumtext COMMENT 'Final prompt sent to the provider for audit display.',
  `raw_response` mediumtext COMMENT 'Original provider response retained for troubleshooting and review transparency.',
  `retry_count` int NOT NULL DEFAULT '0',
  `next_retry_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_review_results_submission` (`submission_id`),
  UNIQUE KEY `uk_ai_review_results_effective_run` (`effective_run_id`),
  KEY `idx_ai_review_results_status` (`status`),
  KEY `fk_ai_review_results_provider` (`provider_id`),
  KEY `idx_ai_review_results_decision_status` (`decision`,`status`),
  KEY `idx_ai_review_results_retry` (`status`,`next_retry_at`),
  CONSTRAINT `fk_ai_review_results_effective_run` FOREIGN KEY (`effective_run_id`) REFERENCES `agent_runs` (`id`),
  CONSTRAINT `fk_ai_review_results_provider` FOREIGN KEY (`provider_id`) REFERENCES `llm_providers` (`id`),
  CONSTRAINT `fk_ai_review_results_submission` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `chk_ai_review_results_decision` CHECK (((`decision` is null) or (`decision` in (_utf8mb4'PASS',_utf8mb4'RETURN',_utf8mb4'MANUAL_REVIEW')))),
  CONSTRAINT `chk_ai_review_results_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'RUNNING',_utf8mb4'SUCCESS',_utf8mb4'FAILED',_utf8mb4'RATE_LIMITED',_utf8mb4'MANUAL_REQUIRED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Business-level AI review conclusion for a submission; agent_runs stores execution details.';
CREATE TABLE `assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `dataset_item_id` bigint NOT NULL,
  `labeler_id` bigint NOT NULL,
  `template_version_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'CLAIMED',
  `draft_answer_json` json DEFAULT NULL COMMENT 'Latest server-side draft answer; Redis may cache the same draft for faster autosave.',
  `draft_version` int NOT NULL DEFAULT '1',
  `claimed_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `submitted_at` datetime(3) DEFAULT NULL,
  `returned_at` datetime(3) DEFAULT NULL,
  `ai_returned_at` datetime(3) DEFAULT NULL,
  `approved_at` datetime(3) DEFAULT NULL,
  `cancelled_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_assignments_item_labeler` (`dataset_item_id`,`labeler_id`),
  KEY `idx_assignments_labeler_status` (`labeler_id`,`status`),
  KEY `idx_assignments_task_status` (`task_id`,`status`),
  KEY `fk_assignments_template_version` (`template_version_id`),
  CONSTRAINT `fk_assignments_item` FOREIGN KEY (`dataset_item_id`) REFERENCES `dataset_items` (`id`),
  CONSTRAINT `fk_assignments_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_assignments_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `fk_assignments_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `template_versions` (`id`),
  CONSTRAINT `chk_assignments_status` CHECK ((`status` in (_utf8mb4'CLAIMED',_utf8mb4'DRAFTING',_utf8mb4'SUBMITTED',_utf8mb4'AI_RETURNED',_utf8mb4'RETURNED',_utf8mb4'APPROVED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Claim record and draft state for one labeler on one dataset item.';
CREATE TABLE `audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_type` varchar(64) NOT NULL,
  `biz_id` bigint NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `actor_id` bigint DEFAULT NULL,
  `action` varchar(64) NOT NULL,
  `before_json` json DEFAULT NULL COMMENT 'Business object snapshot before the action when available.',
  `after_json` json DEFAULT NULL COMMENT 'Business object snapshot after the action when available.',
  `trace_id` varchar(128) DEFAULT NULL,
  `agent_run_id` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_biz` (`biz_type`,`biz_id`,`created_at`),
  KEY `idx_audit_logs_actor` (`actor_id`,`created_at`),
  KEY `idx_audit_logs_trace` (`trace_id`),
  KEY `idx_audit_logs_agent_run` (`agent_run_id`,`created_at`),
  CONSTRAINT `fk_audit_logs_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_audit_logs_agent_run` FOREIGN KEY (`agent_run_id`) REFERENCES `agent_runs` (`id`),
  CONSTRAINT `chk_audit_logs_actor_type` CHECK ((`actor_type` in (_utf8mb4'USER',_utf8mb4'SYSTEM_AGENT')))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only audit trail for state transitions and critical business operations.';
CREATE TABLE `conflict_groups` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `dataset_item_id` bigint NOT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'CONFLICTED',
  `consensus_score` decimal(6,3) DEFAULT NULL COMMENT 'Calculated agreement score across overlapping submissions.',
  `golden_submission_id` bigint DEFAULT NULL COMMENT 'Reviewer-selected golden submission for conflicted or overlapping labels.',
  `resolved_by` bigint DEFAULT NULL,
  `resolved_reason` text,
  `resolved_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_conflict_groups_task_item` (`task_id`,`dataset_item_id`),
  KEY `idx_conflict_groups_status` (`status`),
  KEY `fk_conflict_groups_item` (`dataset_item_id`),
  KEY `fk_conflict_groups_golden_submission` (`golden_submission_id`),
  KEY `fk_conflict_groups_resolved_by` (`resolved_by`),
  CONSTRAINT `fk_conflict_groups_golden_submission` FOREIGN KEY (`golden_submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `fk_conflict_groups_item` FOREIGN KEY (`dataset_item_id`) REFERENCES `dataset_items` (`id`),
  CONSTRAINT `fk_conflict_groups_resolved_by` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_conflict_groups_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_conflict_groups_status` CHECK ((`status` in (_utf8mb4'NONE',_utf8mb4'CONSENSUS_REACHED',_utf8mb4'CONFLICTED',_utf8mb4'RESOLVED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Conflict and consensus resolution for multi-labeler overlap.';
CREATE TABLE `dataset_files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `file_id` bigint NOT NULL,
  `file_format` varchar(20) NOT NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_dataset_files_task` (`task_id`),
  KEY `fk_dataset_files_file` (`file_id`),
  KEY `fk_dataset_files_created_by` (`created_by`),
  CONSTRAINT `fk_dataset_files_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_dataset_files_file` FOREIGN KEY (`file_id`) REFERENCES `object_files` (`id`),
  CONSTRAINT `fk_dataset_files_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_dataset_files_format` CHECK ((`file_format` in (_utf8mb4'JSON',_utf8mb4'JSONL',_utf8mb4'EXCEL',_utf8mb4'CSV')))
) ENGINE=InnoDB AUTO_INCREMENT=900411 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `dataset_import_jobs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `dataset_file_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `import_mode` varchar(20) NOT NULL DEFAULT 'APPEND',
  `total_count` int NOT NULL DEFAULT '0',
  `success_count` int NOT NULL DEFAULT '0',
  `failed_count` int NOT NULL DEFAULT '0',
  `error_report_file_id` bigint DEFAULT NULL,
  `error_message` text,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_dataset_import_jobs_task` (`task_id`,`status`),
  KEY `fk_import_jobs_dataset_file` (`dataset_file_id`),
  KEY `fk_import_jobs_error_file` (`error_report_file_id`),
  KEY `fk_import_jobs_created_by` (`created_by`),
  CONSTRAINT `fk_import_jobs_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_import_jobs_dataset_file` FOREIGN KEY (`dataset_file_id`) REFERENCES `dataset_files` (`id`),
  CONSTRAINT `fk_import_jobs_error_file` FOREIGN KEY (`error_report_file_id`) REFERENCES `object_files` (`id`),
  CONSTRAINT `fk_import_jobs_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_import_jobs_mode` CHECK ((`import_mode` in (_utf8mb4'APPEND',_utf8mb4'OVERWRITE'))),
  CONSTRAINT `chk_import_jobs_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'RUNNING',_utf8mb4'SUCCESS',_utf8mb4'FAILED',_utf8mb4'PARTIAL_SUCCESS')))
) ENGINE=InnoDB AUTO_INCREMENT=900509 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `dataset_item_change_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `item_id` bigint DEFAULT NULL,
  `change_type` varchar(32) NOT NULL,
  `before_json` json DEFAULT NULL,
  `after_json` json DEFAULT NULL,
  `json_patch` json DEFAULT NULL,
  `actor_id` bigint NOT NULL,
  `failure_reason` text,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_item_change_logs_task` (`task_id`,`created_at`),
  KEY `idx_item_change_logs_item` (`item_id`),
  KEY `fk_item_change_logs_actor` (`actor_id`),
  CONSTRAINT `fk_item_change_logs_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_item_change_logs_item` FOREIGN KEY (`item_id`) REFERENCES `dataset_items` (`id`),
  CONSTRAINT `fk_item_change_logs_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=900702 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `dataset_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `external_id` varchar(128) NOT NULL,
  `dataset_type` varchar(40) NOT NULL,
  `item_json` json NOT NULL COMMENT 'Normalized dataset payload, independent from original JSON/JSONL/Excel file format.',
  `metadata_json` json DEFAULT NULL,
  `assigned_count` int NOT NULL DEFAULT '0',
  `submitted_count` int NOT NULL DEFAULT '0',
  `approved_count` int NOT NULL DEFAULT '0',
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `active_external_id` varchar(128) GENERATED ALWAYS AS ((case when (`deleted` = 0) then `external_id` else NULL end)) STORED,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dataset_items_task_external` (`task_id`,`active_external_id`),
  KEY `idx_dataset_items_claim` (`task_id`,`deleted`,`assigned_count`),
  KEY `idx_dataset_items_type` (`task_id`,`dataset_type`),
  CONSTRAINT `fk_dataset_items_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_dataset_items_type` CHECK ((`dataset_type` in (_utf8mb4'QA_QUALITY',_utf8mb4'PREFERENCE_COMPARE')))
) ENGINE=InnoDB AUTO_INCREMENT=900602 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Dataset items available for labeler claim and review.';
CREATE TABLE `export_jobs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `requested_by` bigint NOT NULL,
  `export_format` varchar(20) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `include_ai_review` tinyint(1) NOT NULL DEFAULT '0',
  `include_audit_trail` tinyint(1) NOT NULL DEFAULT '0',
  `include_review_comment` tinyint(1) NOT NULL DEFAULT '0',
  `include_labeler_info` tinyint(1) NOT NULL DEFAULT '0',
  `field_mapping_json` json DEFAULT NULL COMMENT 'Export field mapping array: source JSONPath, target name, formatter, and include flags.',
  `result_file_id` bigint DEFAULT NULL,
  `download_url` varchar(1000) DEFAULT NULL,
  `error_message` text,
  `started_at` datetime(3) DEFAULT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_export_jobs_task` (`task_id`,`created_at`),
  KEY `idx_export_jobs_status` (`status`),
  KEY `fk_export_jobs_result_file` (`result_file_id`),
  KEY `idx_export_jobs_requested_by` (`requested_by`,`created_at`),
  CONSTRAINT `fk_export_jobs_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_export_jobs_result_file` FOREIGN KEY (`result_file_id`) REFERENCES `object_files` (`id`),
  CONSTRAINT `fk_export_jobs_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_export_jobs_format` CHECK ((`export_format` in (_utf8mb4'JSON',_utf8mb4'JSONL',_utf8mb4'CSV',_utf8mb4'EXCEL'))),
  CONSTRAINT `chk_export_jobs_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'RUNNING',_utf8mb4'SUCCESS',_utf8mb4'FAILED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Async export configuration and output file metadata.';
CREATE TABLE `labeler_contribution_stats` (
  `labeler_id` bigint NOT NULL,
  `claimed_count` int NOT NULL DEFAULT '0',
  `submitted_count` int NOT NULL DEFAULT '0',
  `pending_review_count` int NOT NULL DEFAULT '0',
  `approved_count` int NOT NULL DEFAULT '0',
  `rejected_count` int NOT NULL DEFAULT '0',
  `total_reward` decimal(14,2) NOT NULL DEFAULT '0.00',
  `today_submitted_count` int NOT NULL DEFAULT '0',
  `last_submit_date` date DEFAULT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`labeler_id`),
  CONSTRAINT `fk_contribution_stats_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `labeler_daily_stats` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `labeler_id` bigint NOT NULL,
  `stat_date` date NOT NULL,
  `submitted_count` int NOT NULL DEFAULT '0',
  `approved_count` int NOT NULL DEFAULT '0',
  `rejected_count` int NOT NULL DEFAULT '0',
  `reward_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_labeler_daily_stats_date` (`labeler_id`,`stat_date`),
  KEY `idx_labeler_daily_stats_date` (`stat_date`),
  CONSTRAINT `fk_labeler_daily_stats_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_labeler_daily_stats_counts` CHECK (((`submitted_count` >= 0) and (`approved_count` >= 0) and (`rejected_count` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Daily labeler contribution snapshot for trend charts.';
CREATE TABLE `labeler_task_stats` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `labeler_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `claimed_count` int NOT NULL DEFAULT '0',
  `submitted_count` int NOT NULL DEFAULT '0',
  `approved_count` int NOT NULL DEFAULT '0',
  `rejected_count` int NOT NULL DEFAULT '0',
  `total_reward` decimal(14,2) NOT NULL DEFAULT '0.00',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_labeler_task_stats` (`labeler_id`,`task_id`),
  KEY `idx_labeler_task_stats_task` (`task_id`),
  CONSTRAINT `fk_labeler_task_stats_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_labeler_task_stats_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `llm_providers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `provider_code` varchar(64) NOT NULL,
  `provider_name` varchar(100) NOT NULL,
  `base_url` varchar(500) NOT NULL,
  `encrypted_api_key` text,
  `default_model` varchar(128) NOT NULL,
  `custom_headers_json` json DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `platform_rate_limit_per_minute` int DEFAULT NULL,
  `task_rate_limit_per_minute` int DEFAULT NULL,
  `user_rate_limit_per_minute` int DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_llm_providers_code` (`provider_code`),
  KEY `idx_llm_providers_enabled` (`enabled`),
  KEY `fk_llm_providers_created_by` (`created_by`),
  CONSTRAINT `fk_llm_providers_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `object_files` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint DEFAULT NULL,
  `bucket_name` varchar(128) NOT NULL,
  `object_key` varchar(512) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `content_type` varchar(128) DEFAULT NULL,
  `file_size` bigint NOT NULL DEFAULT '0',
  `checksum` varchar(128) DEFAULT NULL,
  `storage_provider` varchar(32) NOT NULL DEFAULT 'MINIO',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_object_files_object` (`bucket_name`,`object_key`),
  KEY `idx_object_files_owner` (`owner_id`),
  CONSTRAINT `fk_object_files_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=900400 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `review_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `submission_id` bigint NOT NULL,
  `review_task_id` bigint DEFAULT NULL COMMENT 'Review queue item this action belongs to; nullable for legacy/direct audit actions.',
  `reviewer_id` bigint NOT NULL,
  `target_reviewer_id` bigint DEFAULT NULL COMMENT 'Reviewer assigned by ASSIGN_REVIEWER action; reviewer_id is the actor who performed the assignment.',
  `action` varchar(32) NOT NULL,
  `review_level` int NOT NULL DEFAULT '1',
  `comment` text,
  `reason` text,
  `before_status` varchar(20) DEFAULT NULL,
  `after_status` varchar(20) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_review_records_submission` (`submission_id`,`created_at`),
  KEY `idx_review_records_reviewer` (`reviewer_id`,`created_at`),
  KEY `idx_review_records_target_reviewer` (`target_reviewer_id`,`created_at`),
  KEY `fk_review_records_review_task` (`review_task_id`),
  CONSTRAINT `fk_review_records_review_task` FOREIGN KEY (`review_task_id`) REFERENCES `review_tasks` (`id`),
  CONSTRAINT `fk_review_records_reviewer` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_review_records_submission` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `fk_review_records_target_reviewer` FOREIGN KEY (`target_reviewer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_review_records_action` CHECK ((`action` in (_utf8mb4'APPROVE',_utf8mb4'REJECT',_utf8mb4'RESOLVE_CONFLICT',_utf8mb4'MARK_MANUAL_REQUIRED',_utf8mb4'ASSIGN_REVIEWER')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only human review actions and assignment audit records.';
CREATE TABLE `review_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `submission_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `review_level` int NOT NULL DEFAULT '1',
  `assigned_reviewer_id` bigint NOT NULL,
  `assigned_by` bigint DEFAULT NULL,
  `status` varchar(24) NOT NULL DEFAULT 'PENDING',
  `review_version` int NOT NULL DEFAULT '1' COMMENT 'Optimistic lock version for concurrent reviewer actions.',
  `assigned_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `due_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_tasks_submission_level` (`submission_id`,`review_level`),
  KEY `idx_review_tasks_reviewer_status` (`assigned_reviewer_id`,`status`,`due_at`),
  KEY `idx_review_tasks_task_level` (`task_id`,`review_level`,`status`),
  KEY `fk_review_tasks_assigned_by` (`assigned_by`),
  CONSTRAINT `fk_review_tasks_assigned_by` FOREIGN KEY (`assigned_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_review_tasks_assigned_reviewer` FOREIGN KEY (`assigned_reviewer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_review_tasks_submission` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `fk_review_tasks_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_review_tasks_level` CHECK ((`review_level` between 1 and 3)),
  CONSTRAINT `chk_review_tasks_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'IN_REVIEW',_utf8mb4'APPROVED',_utf8mb4'REJECTED',_utf8mb4'TRANSFERRED',_utf8mb4'CANCELLED'))),
  CONSTRAINT `chk_review_tasks_version` CHECK ((`review_version` >= 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Reviewer work queue for batch assignment and level 1/2/3 review flow.';
CREATE TABLE `reward_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `labeler_id` bigint NOT NULL,
  `submission_id` bigint NOT NULL,
  `assignment_id` bigint NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `direction` varchar(16) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `source_event_id` varchar(128) NOT NULL,
  `reward_type` varchar(32) NOT NULL DEFAULT 'SUBMISSION_APPROVED',
  `positive_submission_id` bigint GENERATED ALWAYS AS ((case when (`direction` = _utf8mb4'CREDIT') then `submission_id` else NULL end)) STORED COMMENT 'Idempotency key: one positive reward per submission.',
  `positive_assignment_id` bigint GENERATED ALWAYS AS ((case when (`direction` = _utf8mb4'CREDIT') then `assignment_id` else NULL end)) STORED COMMENT 'Idempotency key: one effective positive reward per assignment across versions.',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reward_ledger_event` (`source_event_id`),
  UNIQUE KEY `uk_reward_ledger_positive_submission` (`positive_submission_id`),
  UNIQUE KEY `uk_reward_ledger_positive_assignment` (`positive_assignment_id`),
  KEY `idx_reward_ledger_labeler` (`labeler_id`,`created_at`),
  KEY `idx_reward_ledger_task` (`task_id`,`created_at`),
  KEY `fk_reward_ledger_submission` (`submission_id`),
  KEY `fk_reward_ledger_assignment` (`assignment_id`),
  CONSTRAINT `fk_reward_ledger_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `assignments` (`id`),
  CONSTRAINT `fk_reward_ledger_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_reward_ledger_submission` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`),
  CONSTRAINT `fk_reward_ledger_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_reward_ledger_amount` CHECK ((`amount` >= 0)),
  CONSTRAINT `chk_reward_ledger_direction` CHECK ((`direction` in (_utf8mb4'CREDIT',_utf8mb4'DEBIT'))),
  CONSTRAINT `chk_reward_ledger_type` CHECK ((`reward_type` in (_utf8mb4'SUBMISSION_APPROVED',_utf8mb4'GOLDEN_SELECTED',_utf8mb4'REWARD_REVERSED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only virtual reward ledger; reversals are negative rows, not updates.';
CREATE TABLE `reward_rules` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `effective_version` int NOT NULL COMMENT 'Reward rule version effective for newly approved data; historical ledgers are not rewritten.',
  `reward_mode` varchar(32) NOT NULL DEFAULT 'APPROVED_ITEM',
  `unit_reward` decimal(12,2) NOT NULL DEFAULT '0.00',
  `reward_currency` varchar(32) NOT NULL DEFAULT 'POINT',
  `reward_visible` tinyint(1) NOT NULL DEFAULT '1',
  `effective_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reward_rules_task_version` (`task_id`,`effective_version`),
  KEY `idx_reward_rules_task` (`task_id`),
  KEY `fk_reward_rules_created_by` (`created_by`),
  CONSTRAINT `fk_reward_rules_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_reward_rules_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `chk_reward_rules_effective_version` CHECK ((`effective_version` >= 1)),
  CONSTRAINT `chk_reward_rules_mode` CHECK ((`reward_mode` = _utf8mb4'APPROVED_ITEM')),
  CONSTRAINT `chk_reward_rules_unit_reward` CHECK ((`unit_reward` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Versioned virtual reward configuration for a task.';
CREATE TABLE `submissions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `assignment_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `dataset_item_id` bigint NOT NULL,
  `labeler_id` bigint NOT NULL,
  `template_version_id` bigint NOT NULL,
  `version_no` int NOT NULL,
  `answer_json` json NOT NULL,
  `answer_hash` char(64) NOT NULL,
  `status` varchar(20) NOT NULL,
  `conflict_status` varchar(24) NOT NULL DEFAULT 'NONE',
  `current_review_level` int NOT NULL DEFAULT '1' COMMENT 'Current human review stage: 1 initial review, 2 second review, 3 final review.',
  `review_flow_status` varchar(24) NOT NULL DEFAULT 'UNASSIGNED' COMMENT 'Human review queue state, separate from submission business status.',
  `assigned_reviewer_id` bigint DEFAULT NULL COMMENT 'Current reviewer owner for "assigned to me" filtering; history is stored in review_tasks/review_records.',
  `review_version` int NOT NULL DEFAULT '1' COMMENT 'Optimistic lock version for reviewer state transitions.',
  `is_golden` tinyint(1) NOT NULL DEFAULT '0',
  `golden_dataset_item_id` bigint GENERATED ALWAYS AS ((case when (`is_golden` = 1) then `dataset_item_id` else NULL end)) STORED,
  `submitted_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_submissions_assignment_version` (`assignment_id`,`version_no`),
  UNIQUE KEY `uk_submissions_golden_item` (`golden_dataset_item_id`),
  KEY `idx_submissions_review` (`status`,`conflict_status`,`submitted_at`),
  KEY `idx_submissions_assigned_reviewer` (`assigned_reviewer_id`,`review_flow_status`,`status`),
  KEY `idx_submissions_task_item` (`task_id`,`dataset_item_id`),
  KEY `idx_submissions_labeler` (`labeler_id`,`status`),
  KEY `fk_submissions_item` (`dataset_item_id`),
  KEY `fk_submissions_template_version` (`template_version_id`),
  KEY `idx_submissions_task_review` (`task_id`,`status`,`conflict_status`,`submitted_at`),
  KEY `idx_submissions_export` (`task_id`,`status`,`is_golden`,`submitted_at`),
  KEY `idx_submissions_labeler_time` (`labeler_id`,`submitted_at`),
  CONSTRAINT `fk_submissions_assigned_reviewer` FOREIGN KEY (`assigned_reviewer_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_submissions_assignment` FOREIGN KEY (`assignment_id`) REFERENCES `assignments` (`id`),
  CONSTRAINT `fk_submissions_item` FOREIGN KEY (`dataset_item_id`) REFERENCES `dataset_items` (`id`),
  CONSTRAINT `fk_submissions_labeler` FOREIGN KEY (`labeler_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_submissions_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `fk_submissions_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `template_versions` (`id`),
  CONSTRAINT `chk_submissions_conflict_status` CHECK ((`conflict_status` in (_utf8mb4'NONE',_utf8mb4'CONSENSUS_REACHED',_utf8mb4'CONFLICTED',_utf8mb4'RESOLVED'))),
  CONSTRAINT `chk_submissions_review_flow` CHECK ((`review_flow_status` in (_utf8mb4'UNASSIGNED',_utf8mb4'ASSIGNED',_utf8mb4'IN_REVIEW',_utf8mb4'LEVEL_APPROVED',_utf8mb4'FINAL_APPROVED',_utf8mb4'REJECTED',_utf8mb4'CANCELLED'))),
  CONSTRAINT `chk_submissions_review_level` CHECK ((`current_review_level` between 1 and 3)),
  CONSTRAINT `chk_submissions_review_version` CHECK ((`review_version` >= 1)),
  CONSTRAINT `chk_submissions_status` CHECK ((`status` in (_utf8mb4'SUBMITTED',_utf8mb4'AI_REVIEWING',_utf8mb4'AI_REJECTED',_utf8mb4'PENDING_FINAL',_utf8mb4'APPROVED',_utf8mb4'REJECTED',_utf8mb4'SUPERSEDED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable submission versions and current review routing state.';
CREATE TABLE `task_stats` (
  `task_id` bigint NOT NULL,
  `item_count` int NOT NULL DEFAULT '0',
  `assigned_count` int NOT NULL DEFAULT '0',
  `submitted_count` int NOT NULL DEFAULT '0',
  `pending_review_count` int NOT NULL DEFAULT '0',
  `approved_count` int NOT NULL DEFAULT '0',
  `rejected_count` int NOT NULL DEFAULT '0',
  `conflict_count` int NOT NULL DEFAULT '0',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`task_id`),
  CONSTRAINT `fk_task_stats_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `task_tags` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `tag_name` varchar(64) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_tags_task_tag` (`task_id`,`tag_name`),
  KEY `idx_task_tags_tag_task` (`tag_name`,`task_id`),
  CONSTRAINT `fk_task_tags_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text,
  `instruction_rich_text` mediumtext,
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `quota` int NOT NULL,
  `claimed_count` int NOT NULL DEFAULT '0',
  `overlap_count` int NOT NULL DEFAULT '1',
  `deadline_at` datetime(3) NOT NULL,
  `published_template_version_id` bigint DEFAULT NULL,
  `ai_review_config_id` bigint DEFAULT NULL COMMENT 'Current AI review config used when the task is published or submitted.',
  `reward_visible` tinyint(1) NOT NULL DEFAULT '1',
  `published_at` datetime(3) DEFAULT NULL,
  `ended_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_tasks_owner_status` (`owner_id`,`status`),
  KEY `idx_tasks_status_deadline` (`status`,`deadline_at`),
  KEY `idx_tasks_template_version` (`published_template_version_id`),
  KEY `idx_tasks_ai_review_config` (`ai_review_config_id`),
  FULLTEXT KEY `ft_tasks_search` (`title`,`description`),
  CONSTRAINT `fk_tasks_ai_review_config` FOREIGN KEY (`ai_review_config_id`) REFERENCES `ai_review_configs` (`id`),
  CONSTRAINT `fk_tasks_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_tasks_published_template_version` FOREIGN KEY (`published_template_version_id`) REFERENCES `template_versions` (`id`),
  CONSTRAINT `chk_tasks_overlap` CHECK ((`overlap_count` >= 1)),
  CONSTRAINT `chk_tasks_quota` CHECK ((`quota` > 0)),
  CONSTRAINT `chk_tasks_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'PUBLISHED',_utf8mb4'PAUSED',_utf8mb4'ENDED')))
) ENGINE=InnoDB AUTO_INCREMENT=900204 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Task lifecycle and publish-time references.';
CREATE TABLE `template_versions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NOT NULL,
  `task_id` bigint NOT NULL,
  `version_no` int NOT NULL,
  `schema_json` json NOT NULL COMMENT 'Frozen renderer schema: layout, components, ShowItem bindings, LlmTrigger config, and validation rules.',
  `published_snapshot` tinyint(1) NOT NULL DEFAULT '0',
  `change_note` varchar(500) DEFAULT NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_template_versions_template_version` (`template_id`,`version_no`),
  KEY `idx_template_versions_task` (`task_id`),
  KEY `fk_template_versions_created_by` (`created_by`),
  CONSTRAINT `fk_template_versions_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_template_versions_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`),
  CONSTRAINT `fk_template_versions_template` FOREIGN KEY (`template_id`) REFERENCES `templates` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable template schema versions used by owner preview, labeler rendering, and backend validation.';
CREATE TABLE `templates` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint NOT NULL,
  `name` varchar(200) NOT NULL,
  `current_version_no` int NOT NULL DEFAULT '0',
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_templates_task` (`task_id`),
  KEY `fk_templates_created_by` (`created_by`),
  CONSTRAINT `fk_templates_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_templates_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `role_code` varchar(32) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_roles_user_role` (`user_id`,`role_code`),
  KEY `idx_user_roles_role` (`role_code`),
  CONSTRAINT `fk_user_roles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `chk_user_roles_code` CHECK ((`role_code` in (_utf8mb4'ADMIN',_utf8mb4'OWNER',_utf8mb4'LABELER',_utf8mb4'REVIEWER',_utf8mb4'SYSTEM_AGENT')))
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `username` varchar(64) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `user_type` varchar(20) NOT NULL DEFAULT 'USER',
  `login_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `token_version` int NOT NULL DEFAULT '1',
  `display_name` varchar(100) DEFAULT NULL,
  `avatar_url` varchar(500) DEFAULT NULL,
  `last_login_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_username` (`username`),
  UNIQUE KEY `uk_users_email` (`email`),
  KEY `idx_users_enabled` (`enabled`),
  CONSTRAINT `chk_users_user_type` CHECK ((`user_type` in (_utf8mb4'USER',_utf8mb4'SYSTEM')))
) ENGINE=InnoDB AUTO_INCREMENT=900107 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
