CREATE TABLE submissions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  assignment_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  dataset_item_id BIGINT NOT NULL,
  labeler_id BIGINT NOT NULL,
  template_version_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  answer_json JSON NOT NULL,
  answer_hash CHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL,
  submitted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_submissions_assignment_version (assignment_id, version_no),
  KEY idx_submissions_assignment_status (assignment_id, status),
  KEY idx_submissions_task_item (task_id, dataset_item_id),
  KEY idx_submissions_labeler (labeler_id, status),
  CONSTRAINT fk_submissions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id),
  CONSTRAINT fk_submissions_task FOREIGN KEY (task_id) REFERENCES tasks(id),
  CONSTRAINT fk_submissions_item FOREIGN KEY (dataset_item_id) REFERENCES dataset_items(id),
  CONSTRAINT fk_submissions_labeler FOREIGN KEY (labeler_id) REFERENCES users(id),
  CONSTRAINT fk_submissions_template_version FOREIGN KEY (template_version_id) REFERENCES template_versions(id),
  CONSTRAINT chk_submissions_status CHECK (status IN ('SUBMITTED', 'AI_REVIEWING', 'AI_REJECTED', 'PENDING_FINAL', 'APPROVED', 'REJECTED', 'SUPERSEDED')),
  CONSTRAINT chk_submissions_version CHECK (version_no >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable labeler answer submission versions.';
