-- Add Chinese comments for all application business tables and columns.

alter table users comment = '用户账号表，存储登录身份和基础资料。';
alter table users modify column id bigint auto_increment comment '主键ID';
alter table users modify column username varchar(64) not null comment 'username：标识';
alter table users modify column email varchar(255) not null comment 'email：标识';
alter table users modify column password_hash varchar(255) null comment '密码哈希';
alter table users modify column user_type varchar(20) default 'USER' not null comment '用户类型';
alter table users modify column login_enabled tinyint(1) default 1 not null comment '是否登录启用状态';
alter table users modify column enabled tinyint(1) default 1 not null comment '启用状态';
alter table users modify column token_version int default 1 not null comment '令牌版本';
alter table users modify column display_name varchar(100) null comment '展示名称';
alter table users modify column avatar_url varchar(500) null comment '头像地址';
alter table users modify column last_login_at datetime(3) null comment '最近登录时间';
alter table users modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table users modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table labeler_contribution_stats comment = '标注员贡献统计表，存储标注员贡献统计相关业务数据。';
alter table labeler_contribution_stats modify column labeler_id bigint not null comment '标注员ID';
alter table labeler_contribution_stats modify column claimed_count int default 0 not null comment '领取数量';
alter table labeler_contribution_stats modify column submitted_count int default 0 not null comment '提交数量';
alter table labeler_contribution_stats modify column pending_review_count int default 0 not null comment '待处理审核数量';
alter table labeler_contribution_stats modify column approved_count int default 0 not null comment '通过数量';
alter table labeler_contribution_stats modify column rejected_count int default 0 not null comment '拒绝数量';
alter table labeler_contribution_stats modify column total_reward decimal(14, 2) default 0.00 not null comment '总计奖励';
alter table labeler_contribution_stats modify column today_submitted_count int default 0 not null comment 'today提交数量';
alter table labeler_contribution_stats modify column last_submit_date date null comment '最近submit时间';
alter table labeler_contribution_stats modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table labeler_daily_stats comment = '标注员每日统计表，存储标注员每日统计相关业务数据。';
alter table labeler_daily_stats modify column id bigint auto_increment comment '主键ID';
alter table labeler_daily_stats modify column labeler_id bigint not null comment '标注员ID';
alter table labeler_daily_stats modify column stat_date date not null comment 'stat时间';
alter table labeler_daily_stats modify column submitted_count int default 0 not null comment '提交数量';
alter table labeler_daily_stats modify column approved_count int default 0 not null comment '通过数量';
alter table labeler_daily_stats modify column rejected_count int default 0 not null comment '拒绝数量';
alter table labeler_daily_stats modify column reward_amount decimal(14, 2) default 0.00 not null comment '奖励金额';
alter table labeler_daily_stats modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table labeler_daily_stats modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table llm_providers comment = '大模型服务提供商表，存储大模型服务提供商相关业务数据。';
alter table llm_providers modify column id bigint auto_increment comment '主键ID';
alter table llm_providers modify column provider_code varchar(64) not null comment '服务提供商编码';
alter table llm_providers modify column provider_name varchar(100) not null comment '服务提供商名称';
alter table llm_providers modify column base_url varchar(500) not null comment 'base地址';
alter table llm_providers modify column encrypted_api_key text null comment 'encryptedapi键';
alter table llm_providers modify column default_model varchar(128) not null comment '默认模型';
alter table llm_providers modify column custom_headers_json json null comment '自定义请求头JSON';
alter table llm_providers modify column enabled tinyint(1) default 1 not null comment '启用状态';
alter table llm_providers modify column platform_rate_limit_per_minute int null comment '平台每分钟限流次数';
alter table llm_providers modify column task_rate_limit_per_minute int null comment '任务ratelimitperminute';
alter table llm_providers modify column user_rate_limit_per_minute int null comment '用户ratelimitperminute';
alter table llm_providers modify column created_by bigint null comment '创建人';
alter table llm_providers modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table llm_providers modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table ai_review_configs comment = 'AI审核配置表，存储AI审核配置相关业务数据。';
alter table ai_review_configs modify column id bigint auto_increment comment '主键ID';
alter table ai_review_configs modify column task_id bigint not null comment '任务ID';
alter table ai_review_configs modify column provider_id bigint null comment '服务提供商ID';
alter table ai_review_configs modify column model_name varchar(128) null comment 'model名称';
alter table ai_review_configs modify column enabled tinyint(1) default 1 not null comment '启用状态';
alter table ai_review_configs modify column prompt_template mediumtext null comment '提示词模板';
alter table ai_review_configs modify column output_schema_json json null comment 'output结构JSON';
alter table ai_review_configs modify column dimension_config_json json null comment '维度配置JSON';
alter table ai_review_configs modify column pass_threshold decimal(5, 2) null comment '通过阈值';
alter table ai_review_configs modify column reject_threshold decimal(5, 2) null comment '拒绝阈值';
alter table ai_review_configs modify column manual_threshold decimal(5, 2) null comment '人工阈值';
alter table ai_review_configs modify column ai_reject_action varchar(24) default 'SUGGEST_ONLY' not null comment 'AI拒绝动作';
alter table ai_review_configs modify column max_retry int default 3 not null comment '最大重试';
alter table ai_review_configs modify column created_by bigint not null comment '创建人';
alter table ai_review_configs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table ai_review_configs modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table object_files comment = '对象文件表，存储对象文件相关业务数据。';
alter table object_files modify column id bigint auto_increment comment '主键ID';
alter table object_files modify column owner_id bigint null comment '拥有者ID';
alter table object_files modify column bucket_name varchar(128) not null comment '存储桶名称';
alter table object_files modify column object_key varchar(512) not null comment '对象键';
alter table object_files modify column original_filename varchar(255) not null comment '原始文件名';
alter table object_files modify column content_type varchar(128) null comment '内容类型';
alter table object_files modify column file_size bigint default 0 not null comment '文件大小';
alter table object_files modify column checksum varchar(128) null comment '校验值';
alter table object_files modify column storage_provider varchar(32) default 'MINIO' not null comment '存储服务提供商';
alter table object_files modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table tasks comment = '标注任务表，存储任务生命周期、配额和配置。';
alter table tasks modify column id bigint auto_increment comment '主键ID';
alter table tasks modify column owner_id bigint not null comment '拥有者ID';
alter table tasks modify column title varchar(200) not null comment '标题';
alter table tasks modify column description text null comment '描述';
alter table tasks modify column instruction_rich_text mediumtext null comment '说明富文本文本';
alter table tasks modify column status varchar(20) default 'DRAFT' not null comment 'status状态';
alter table tasks modify column quota int not null comment '配额';
alter table tasks modify column claimed_count int default 0 not null comment '领取数量';
alter table tasks modify column overlap_count int default 1 not null comment '重叠数量';
alter table tasks modify column deadline_at datetime(3) not null comment '截止时间';
alter table tasks modify column published_template_version_id bigint null comment '发布模板版本ID';
alter table tasks modify column ai_review_config_id bigint null comment 'AI审核配置ID';
alter table tasks modify column reward_visible tinyint(1) default 1 not null comment '是否奖励可见';
alter table tasks modify column published_at datetime(3) null comment '发布时间';
alter table tasks modify column ended_at datetime(3) null comment '结束时间';
alter table tasks modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table tasks modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table dataset_files comment = '数据集文件表，存储数据集文件相关业务数据。';
alter table dataset_files modify column id bigint auto_increment comment '主键ID';
alter table dataset_files modify column task_id bigint not null comment '任务ID';
alter table dataset_files modify column file_id bigint not null comment '文件ID';
alter table dataset_files modify column file_format varchar(20) not null comment '文件格式';
alter table dataset_files modify column created_by bigint not null comment '创建人';
alter table dataset_files modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table dataset_import_jobs comment = '数据集导入作业表，存储数据集导入作业相关业务数据。';
alter table dataset_import_jobs modify column id bigint auto_increment comment '主键ID';
alter table dataset_import_jobs modify column task_id bigint not null comment '任务ID';
alter table dataset_import_jobs modify column dataset_file_id bigint not null comment '数据集文件ID';
alter table dataset_import_jobs modify column status varchar(20) default 'PENDING' not null comment 'status状态';
alter table dataset_import_jobs modify column import_mode varchar(20) default 'APPEND' not null comment '导入模式';
alter table dataset_import_jobs modify column total_count int default 0 not null comment '总计数量';
alter table dataset_import_jobs modify column success_count int default 0 not null comment '成功数量';
alter table dataset_import_jobs modify column failed_count int default 0 not null comment '失败数量';
alter table dataset_import_jobs modify column error_report_file_id bigint null comment '错误report文件ID';
alter table dataset_import_jobs modify column error_message text null comment '错误信息';
alter table dataset_import_jobs modify column started_at datetime(3) null comment '开始时间';
alter table dataset_import_jobs modify column finished_at datetime(3) null comment '完成时间';
alter table dataset_import_jobs modify column created_by bigint not null comment '创建人';
alter table dataset_import_jobs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table dataset_items comment = '数据集数据条目表，存储数据集数据条目相关业务数据。';
alter table dataset_items modify column id bigint auto_increment comment '主键ID';
alter table dataset_items modify column task_id bigint not null comment '任务ID';
alter table dataset_items modify column external_id varchar(128) not null comment '外部ID';
alter table dataset_items modify column dataset_type varchar(40) not null comment '数据集类型';
alter table dataset_items modify column item_json json not null comment '数据条目JSON';
alter table dataset_items modify column metadata_json json null comment '元数据JSON';
alter table dataset_items modify column assigned_count int default 0 not null comment '分配数量';
alter table dataset_items modify column submitted_count int default 0 not null comment '提交数量';
alter table dataset_items modify column approved_count int default 0 not null comment '通过数量';
alter table dataset_items modify column deleted tinyint(1) default 0 not null comment '删除状态';
alter table dataset_items modify column active_external_id varchar(128) generated always as ((case when (`deleted` = 0) then `external_id` else NULL end)) stored comment '有效外部ID';
alter table dataset_items modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table dataset_items modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table dataset_item_change_logs comment = '数据集数据条目变更日志表，存储数据集数据条目变更日志相关业务数据。';
alter table dataset_item_change_logs modify column id bigint auto_increment comment '主键ID';
alter table dataset_item_change_logs modify column task_id bigint not null comment '任务ID';
alter table dataset_item_change_logs modify column item_id bigint null comment '数据条目ID';
alter table dataset_item_change_logs modify column change_type varchar(32) not null comment '变更类型';
alter table dataset_item_change_logs modify column before_json json null comment '变更前JSON';
alter table dataset_item_change_logs modify column after_json json null comment '变更后JSON';
alter table dataset_item_change_logs modify column json_patch json null comment 'JSON补丁变更内容';
alter table dataset_item_change_logs modify column actor_id bigint not null comment '操作人ID';
alter table dataset_item_change_logs modify column failure_reason text null comment '失败原因';
alter table dataset_item_change_logs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table export_jobs comment = '导出作业表，存储导出作业相关业务数据。';
alter table export_jobs modify column id bigint auto_increment comment '主键ID';
alter table export_jobs modify column task_id bigint not null comment '任务ID';
alter table export_jobs modify column requested_by bigint not null comment '请求人';
alter table export_jobs modify column export_format varchar(20) not null comment '导出格式';
alter table export_jobs modify column status varchar(20) default 'PENDING' not null comment 'status状态';
alter table export_jobs modify column include_ai_review tinyint(1) default 0 not null comment '是否AI审核';
alter table export_jobs modify column include_audit_trail tinyint(1) default 0 not null comment '是否审计轨迹';
alter table export_jobs modify column include_review_comment tinyint(1) default 0 not null comment '是否审核备注';
alter table export_jobs modify column include_labeler_info tinyint(1) default 0 not null comment '是否标注员info';
alter table export_jobs modify column field_mapping_json json null comment '字段映射JSON';
alter table export_jobs modify column result_file_id bigint null comment '结果文件ID';
alter table export_jobs modify column download_url varchar(1000) null comment '下载地址';
alter table export_jobs modify column error_message text null comment '错误信息';
alter table export_jobs modify column trace_id varchar(128) null comment '追踪ID';
alter table export_jobs modify column started_at datetime(3) null comment '开始时间';
alter table export_jobs modify column finished_at datetime(3) null comment '完成时间';
alter table export_jobs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table labeler_task_stats comment = '标注员任务统计表，存储标注员任务统计相关业务数据。';
alter table labeler_task_stats modify column id bigint auto_increment comment '主键ID';
alter table labeler_task_stats modify column labeler_id bigint not null comment '标注员ID';
alter table labeler_task_stats modify column task_id bigint not null comment '任务ID';
alter table labeler_task_stats modify column claimed_count int default 0 not null comment '领取数量';
alter table labeler_task_stats modify column submitted_count int default 0 not null comment '提交数量';
alter table labeler_task_stats modify column approved_count int default 0 not null comment '通过数量';
alter table labeler_task_stats modify column rejected_count int default 0 not null comment '拒绝数量';
alter table labeler_task_stats modify column total_reward decimal(14, 2) default 0.00 not null comment '总计奖励';
alter table labeler_task_stats modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table reward_rules comment = '奖励规则表，存储奖励规则相关业务数据。';
alter table reward_rules modify column id bigint auto_increment comment '主键ID';
alter table reward_rules modify column task_id bigint not null comment '任务ID';
alter table reward_rules modify column effective_version int not null comment '生效版本';
alter table reward_rules modify column reward_mode varchar(32) default 'APPROVED_ITEM' not null comment '奖励模式';
alter table reward_rules modify column unit_reward decimal(12, 2) default 0.00 not null comment '单条奖励';
alter table reward_rules modify column reward_currency varchar(32) default 'POINT' not null comment '奖励币种';
alter table reward_rules modify column reward_visible tinyint(1) default 1 not null comment '是否奖励可见';
alter table reward_rules modify column effective_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '生效时间';
alter table reward_rules modify column created_by bigint not null comment '创建人';
alter table reward_rules modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table task_stats comment = '任务统计表，存储任务统计相关业务数据。';
alter table task_stats modify column task_id bigint not null comment '任务ID';
alter table task_stats modify column item_count int default 0 not null comment '数据条目数量';
alter table task_stats modify column assigned_count int default 0 not null comment '分配数量';
alter table task_stats modify column submitted_count int default 0 not null comment '提交数量';
alter table task_stats modify column pending_review_count int default 0 not null comment '待处理审核数量';
alter table task_stats modify column approved_count int default 0 not null comment '通过数量';
alter table task_stats modify column rejected_count int default 0 not null comment '拒绝数量';
alter table task_stats modify column conflict_count int default 0 not null comment '冲突数量';
alter table task_stats modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table task_tags comment = '任务tags表，存储任务tags相关业务数据。';
alter table task_tags modify column id bigint auto_increment comment '主键ID';
alter table task_tags modify column task_id bigint not null comment '任务ID';
alter table task_tags modify column tag_name varchar(64) not null comment '标签名称';
alter table task_tags modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table templates comment = '模板表，存储模板相关业务数据。';
alter table templates modify column id bigint auto_increment comment '主键ID';
alter table templates modify column task_id bigint not null comment '任务ID';
alter table templates modify column name varchar(200) not null comment '名称';
alter table templates modify column current_version_no int default 0 not null comment '当前版本no';
alter table templates modify column created_by bigint not null comment '创建人';
alter table templates modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table templates modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table template_versions comment = '模板版本表，存储模板版本相关业务数据。';
alter table template_versions modify column id bigint auto_increment comment '主键ID';
alter table template_versions modify column template_id bigint not null comment '模板ID';
alter table template_versions modify column task_id bigint not null comment '任务ID';
alter table template_versions modify column version_no int not null comment '版本no';
alter table template_versions modify column schema_json json not null comment '结构JSON';
alter table template_versions modify column published_snapshot tinyint(1) default 0 not null comment '发布快照';
alter table template_versions modify column change_note varchar(500) null comment '变更note';
alter table template_versions modify column created_by bigint not null comment '创建人';
alter table template_versions modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table assignments comment = '分配表，存储分配相关业务数据。';
alter table assignments modify column id bigint auto_increment comment '主键ID';
alter table assignments modify column task_id bigint not null comment '任务ID';
alter table assignments modify column dataset_item_id bigint not null comment '数据集数据条目ID';
alter table assignments modify column labeler_id bigint not null comment '标注员ID';
alter table assignments modify column template_version_id bigint not null comment '模板版本ID';
alter table assignments modify column status varchar(20) default 'CLAIMED' not null comment 'status状态';
alter table assignments modify column draft_answer_json json null comment '草稿答案JSON';
alter table assignments modify column draft_version int default 1 not null comment '草稿版本';
alter table assignments modify column claimed_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '领取时间';
alter table assignments modify column submitted_at datetime(3) null comment '提交时间';
alter table assignments modify column returned_at datetime(3) null comment '退回时间';
alter table assignments modify column ai_returned_at datetime(3) null comment 'AI退回时间';
alter table assignments modify column approved_at datetime(3) null comment '通过时间';
alter table assignments modify column cancelled_at datetime(3) null comment '取消时间';
alter table assignments modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table submissions comment = '标注提交表，存储答案版本和审核流转状态。';
alter table submissions modify column id bigint auto_increment comment '主键ID';
alter table submissions modify column assignment_id bigint not null comment '分配ID';
alter table submissions modify column task_id bigint not null comment '任务ID';
alter table submissions modify column dataset_item_id bigint not null comment '数据集数据条目ID';
alter table submissions modify column labeler_id bigint not null comment '标注员ID';
alter table submissions modify column template_version_id bigint not null comment '模板版本ID';
alter table submissions modify column version_no int not null comment '版本no';
alter table submissions modify column answer_json json not null comment '答案JSON';
alter table submissions modify column answer_hash char(64) not null comment '答案哈希';
alter table submissions modify column status varchar(20) not null comment 'status状态';
alter table submissions modify column conflict_status varchar(24) default 'NONE' not null comment '冲突状态';
alter table submissions modify column current_review_level int default 1 not null comment '当前审核层级';
alter table submissions modify column review_flow_status varchar(24) default 'UNASSIGNED' not null comment '审核flow状态';
alter table submissions modify column assigned_reviewer_id bigint null comment '分配审核员ID';
alter table submissions modify column review_version int default 1 not null comment '审核版本';
alter table submissions modify column is_golden tinyint(1) default 0 not null comment '是否黄金标准';
alter table submissions modify column golden_dataset_item_id bigint as ((case when (`is_golden` = 1) then `dataset_item_id` else NULL end)) stored comment '黄金标准数据集数据条目ID';
alter table submissions modify column submitted_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '提交时间';
alter table submissions modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table agent_runs comment = '智能体执行表，存储智能体执行相关业务数据。';
alter table agent_runs modify column id bigint auto_increment comment '主键ID';
alter table agent_runs modify column agent_type varchar(32) not null comment '智能体类型';
alter table agent_runs modify column submission_id bigint null comment '提交ID';
alter table agent_runs modify column provider_id bigint null comment '服务提供商ID';
alter table agent_runs modify column model_name varchar(128) null comment 'model名称';
alter table agent_runs modify column prompt_version varchar(64) null comment '提示词版本';
alter table agent_runs modify column input_snapshot json null comment 'input快照';
alter table agent_runs modify column output_snapshot json null comment 'output快照';
alter table agent_runs modify column status varchar(24) default 'PENDING' not null comment 'status状态';
alter table agent_runs modify column error_message text null comment '错误信息';
alter table agent_runs modify column started_at datetime(3) null comment '开始时间';
alter table agent_runs modify column finished_at datetime(3) null comment '完成时间';
alter table agent_runs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table ai_review_results comment = 'AI审核results表，存储AI审核results相关业务数据。';
alter table ai_review_results modify column id bigint auto_increment comment '主键ID';
alter table ai_review_results modify column submission_id bigint not null comment '提交ID';
alter table ai_review_results modify column effective_run_id bigint null comment '生效执行ID';
alter table ai_review_results modify column provider_id bigint null comment '服务提供商ID';
alter table ai_review_results modify column model_name varchar(128) null comment 'model名称';
alter table ai_review_results modify column status varchar(24) default 'PENDING' not null comment 'status状态';
alter table ai_review_results modify column decision varchar(24) null comment '决策';
alter table ai_review_results modify column average_score decimal(6, 3) null comment '平均分数';
alter table ai_review_results modify column dimension_scores json null comment '维度评分';
alter table ai_review_results modify column risk_flags json null comment '风险标记';
alter table ai_review_results modify column suggestion text null comment '建议';
alter table ai_review_results modify column prompt_snapshot mediumtext null comment '提示词快照';
alter table ai_review_results modify column raw_response mediumtext null comment '原始响应';
alter table ai_review_results modify column retry_count int default 0 not null comment '重试数量';
alter table ai_review_results modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table ai_review_results modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table audit_logs comment = '审计日志表，存储审计日志相关业务数据。';
alter table audit_logs modify column id bigint auto_increment comment '主键ID';
alter table audit_logs modify column biz_type varchar(64) not null comment '业务对象类型';
alter table audit_logs modify column biz_id bigint not null comment '业务对象ID';
alter table audit_logs modify column actor_type varchar(32) not null comment '操作人类型';
alter table audit_logs modify column actor_id bigint null comment '操作人ID';
alter table audit_logs modify column action varchar(64) not null comment '动作';
alter table audit_logs modify column before_json json null comment '变更前JSON';
alter table audit_logs modify column after_json json null comment '变更后JSON';
alter table audit_logs modify column trace_id varchar(128) null comment '追踪ID';
alter table audit_logs modify column agent_run_id bigint null comment '智能体执行ID';
alter table audit_logs modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table conflict_groups comment = '冲突分组表，存储冲突分组相关业务数据。';
alter table conflict_groups modify column id bigint auto_increment comment '主键ID';
alter table conflict_groups modify column task_id bigint not null comment '任务ID';
alter table conflict_groups modify column dataset_item_id bigint not null comment '数据集数据条目ID';
alter table conflict_groups modify column status varchar(24) default 'CONFLICTED' not null comment 'status状态';
alter table conflict_groups modify column consensus_score decimal(6, 3) null comment '共识分数';
alter table conflict_groups modify column golden_submission_id bigint null comment '黄金标准提交ID';
alter table conflict_groups modify column resolved_by bigint null comment '解决人';
alter table conflict_groups modify column resolved_reason text null comment '解决原因';
alter table conflict_groups modify column resolved_at datetime(3) null comment '解决时间';
alter table conflict_groups modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table conflict_groups modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table review_tasks comment = '审核任务表，存储审核任务相关业务数据。';
alter table review_tasks modify column id bigint auto_increment comment '主键ID';
alter table review_tasks modify column submission_id bigint not null comment '提交ID';
alter table review_tasks modify column task_id bigint not null comment '任务ID';
alter table review_tasks modify column review_level int default 1 not null comment '审核层级';
alter table review_tasks modify column assigned_reviewer_id bigint not null comment '分配审核员ID';
alter table review_tasks modify column assigned_by bigint null comment '分配人';
alter table review_tasks modify column status varchar(24) default 'PENDING' not null comment 'status状态';
alter table review_tasks modify column review_version int default 1 not null comment '审核版本';
alter table review_tasks modify column assigned_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '分配时间';
alter table review_tasks modify column started_at datetime(3) null comment '开始时间';
alter table review_tasks modify column completed_at datetime(3) null comment '完成时间';
alter table review_tasks modify column due_at datetime(3) null comment '截止时间';
alter table review_tasks modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
alter table review_tasks modify column updated_at datetime(3) default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3) comment '更新时间';

alter table review_records comment = '审核记录表，存储审核记录相关业务数据。';
alter table review_records modify column id bigint auto_increment comment '主键ID';
alter table review_records modify column submission_id bigint not null comment '提交ID';
alter table review_records modify column review_task_id bigint null comment '审核任务ID';
alter table review_records modify column reviewer_id bigint not null comment '审核员ID';
alter table review_records modify column target_reviewer_id bigint null comment '目标审核员ID';
alter table review_records modify column action varchar(32) not null comment '动作';
alter table review_records modify column review_level int default 1 not null comment '审核层级';
alter table review_records modify column comment text null comment '备注';
alter table review_records modify column reason text null comment '原因';
alter table review_records modify column before_status varchar(20) null comment '变更前状态';
alter table review_records modify column after_status varchar(20) null comment '变更后状态';
alter table review_records modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table reward_ledger comment = '奖励流水表，存储奖励流水相关业务数据。';
alter table reward_ledger modify column id bigint auto_increment comment '主键ID';
alter table reward_ledger modify column task_id bigint not null comment '任务ID';
alter table reward_ledger modify column labeler_id bigint not null comment '标注员ID';
alter table reward_ledger modify column submission_id bigint not null comment '提交ID';
alter table reward_ledger modify column assignment_id bigint not null comment '分配ID';
alter table reward_ledger modify column amount decimal(12, 2) not null comment '金额';
alter table reward_ledger modify column direction varchar(16) not null comment '方向';
alter table reward_ledger modify column reason varchar(255) not null comment '原因';
alter table reward_ledger modify column source_event_id varchar(128) not null comment '来源事件ID';
alter table reward_ledger modify column reward_type varchar(32) default 'SUBMISSION_APPROVED' not null comment '奖励类型';
alter table reward_ledger modify column positive_submission_id bigint as ((case when (`direction` = _utf8mb4'CREDIT') then `submission_id` else NULL end)) stored comment '正向提交ID';
alter table reward_ledger modify column positive_assignment_id bigint as ((case when (`direction` = _utf8mb4'CREDIT') then `assignment_id` else NULL end)) stored comment '正向分配ID';
alter table reward_ledger modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';

alter table user_roles comment = '用户角色表，存储用户角色相关业务数据。';
alter table user_roles modify column id bigint auto_increment comment '主键ID';
alter table user_roles modify column user_id bigint not null comment '用户ID';
alter table user_roles modify column role_code varchar(32) not null comment '角色编码';
alter table user_roles modify column created_at datetime(3) default CURRENT_TIMESTAMP(3) not null comment '创建时间';
